import assert from 'node:assert/strict';
import { RANKS, seasonId, rankView, trophyDelta, applyResult, resetSeason, advanceRanked } from '../functions/ranked-core.js';
let checks=0;
for(let rank=0;rank<5;rank++) for(const games of [0,5,20,100,1000]) for(const opponentTotal of [0,100,400,2000]) for(const won of [true,false]) {
  const player={rank,trophies:rank*100+50,games,wins:Math.floor(games*.6)};
  const delta=trophyDelta(player,{trophies:opponentTotal,games:100,wins:70},won);
  const range=won?RANKS[rank].win:RANKS[rank].loss;
  assert.ok(Math.abs(delta)>=range[0] && Math.abs(delta)<=range[1]);checks++;
}
const base={rank:2,trophies:250,games:60,wins:30};
assert.ok(trophyDelta(base,{...base,trophies:450},true)>trophyDelta(base,{...base,trophies:50},true));
assert.ok(trophyDelta(base,{...base,trophies:450},false)>trophyDelta(base,{...base,trophies:50},false));
assert.ok(trophyDelta({...base,games:0,wins:0},base,true)>=trophyDelta(base,base,true));
assert.equal(applyResult({rank:0,trophies:95},15,true).rank,1);
assert.equal(rankView(applyResult({rank:0,trophies:95},15,true)).progress,10);
assert.equal(applyResult({rank:1,trophies:107},-7,false).rank,0);
assert.equal(applyResult({rank:1,trophies:102},-9,false).trophies,93);
assert.equal(applyResult({rank:0,trophies:2},-10,false).trophies,0);
assert.equal(applyResult({rank:4,trophies:900},15,true).rank,4);
assert.equal(seasonId(Date.UTC(2026,8,30,23,59,59)),'2026-09');
assert.equal(seasonId(Date.UTC(2026,9,1)),'2026-10');
const reset=resetSeason({season:'2026-09',rank:4,trophies:445,highestRank:4,seasonGames:20},'2026-10');
assert.equal(reset.trophies,334);assert.equal(reset.rank,3);assert.equal(reset.highestRank,3);assert.equal(reset.seasonGames,0);
assert.deepEqual(resetSeason(reset,'2026-10'),reset);
assert.equal(resetSeason({season:'2026-09',rank:0,trophies:95},'2026-10').trophies,95);
const state={matchId:'test',revision:0,current:0,players:[{name:'A',hands:[1,0],actionUsed:false},{name:'B',hands:[3,0],actionUsed:false}],over:false,turnDeadlineAt:100000};
const proposal=structuredClone(state);proposal.players[1].hands=[4,0];proposal.players[0].actionUsed=true;
let next=advanceRanked(state,proposal,0,1000);
assert.equal(next.over,false);assert.deepEqual(next.players[1].hands,[4,0]);
assert.throws(()=>advanceRanked(state,proposal,1,1000));
assert.throws(()=>advanceRanked(next,{...proposal,players:[proposal.players[0],{...proposal.players[1],hands:[0,0]}]},0,1001));
next=advanceRanked(next,{...next,current:1},0,2000);
assert.equal(next.current,1);assert.equal(next.turnDeadlineAt,32000);
const lethal=structuredClone(next);lethal.players[0].hands=[0,0];
const ended=advanceRanked(next,lethal,1,3000);
assert.equal(ended.over,true);assert.equal(ended.result.winnerIndex,1);
assert.deepEqual(advanceRanked(ended,{},0,500000),ended);
assert.equal(advanceRanked(state,{},1,100001).result.winnerIndex,1);
assert.equal(advanceRanked(state,{result:{reason:'forfeit'}},1,1000).result.winnerIndex,0);
assert.throws(()=>advanceRanked(state,{...state,current:1},0,1000));
console.log(`Ranked regression checks passed (${checks} trophy range combinations plus progression, seasons, move validation, final move, timeout, and forfeit).`);
